global:
  scrape_interval: 2s
  evaluation_interval: 2s
 
scrape_configs:
  - job_name: 'prometheus'
    static_configs:
      - targets: ['prometheus:9090']
  - job_name: 'retail-services'
    metrics_path: '/actuator/prometheus'
    eureka_sd_configs:
      - server: http://localhost:8080
        refresh_interval: 30s
    relabel_configs:
      - source_labels: [__meta_eureka_app_name]
        target_label: job


# n this configuration, Prometheus will discover all services registered with Eureka 
# and scrape metrics from them. The relabel_configs will set the job label to the name of the 
# service as registered in Eureka (__meta_eureka_app_name), so you can still differentiate metrics from different services.